apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  selector:
    matchLabels:
      app: flask-app    # Updated the selector to match the labels in the template
      component: greeting    # Updated the selector to match the labels in the template
  template:
    metadata:
      labels:
        app: flask-app
        component: greeting
    spec:
      containers:
      - name: flask-app
        image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/flask_app:latest
        ports:
        - containerPort: 5000


